"""Shared constants across the dialogue frame extraction pipeline."""

from pathlib import Path

DEFAULT_RAW_VIDEO_DIR: Path = Path("data/raw")
DEFAULT_FRAMES_DIR: Path = Path("data/frames")

DEFAULT_SIMILARITY_THRESHOLD: float = 0.8
DEFAULT_OCR_SIMILARITY_THRESHOLD: float = 0.8
DEFAULT_SAMPLING_INTERVAL_SECONDS: float = 0.3

DEFAULT_VIDEO_OUT_TEMPLATE: str = "%(id)s.%(ext)s"

DEFAULT_LOG_FORMAT: str = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
DEFAULT_LOG_DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S"

DEFAULT_SOCKET_TIMEOUT: int = 30
DEFAULT_NETWORK_RETRIES: int = 5
DEFAULT_CONCURRENT_FRAGMENT_DOWNLOADS: int = 8

OK_RU_DEPRIORITIZED_IP: str = "95.163.61.73"

DEFAULT_AUDIO_DIR: Path = Path("data/audio")
DEFAULT_WHISPER_MODEL_SIZE: str = "tiny"
DEFAULT_AUDIO_SAMPLE_RATE: int = 16000

DEFAULT_WINDOW_PADDING_SECONDS: float = 1.0
DEFAULT_MAX_WINDOW_SEGMENTS: int = 1
DEFAULT_MAX_TRANSCRIPT_CHUNK_SPAN_SECONDS: float = 2.5

DEFAULT_GEMINI_MODEL: str = "gemini-3.6-flash"
DEFAULT_CAPTION_CROP_RATIO: float = 0.33
DEFAULT_MIN_CAPTION_TEXT_LENGTH: int = 3

DEFAULT_GEMINI_REQUESTS_PER_MINUTE: int = 5
DEFAULT_GEMINI_PACING_BUFFER_SECONDS: float = 3.0
DEFAULT_OCR_MAX_ATTEMPTS: int = 5
DEFAULT_OCR_BASE_RETRY_DELAY_SECONDS: float = 2.0

DEFAULT_PROCESSED_DIR: Path = Path("data/processed")
DEFAULT_TRANSCRIPT_CACHE_DIR: Path = Path("data/processed/transcripts")
DEFAULT_OCR_CACHE_DIR: Path = Path("data/processed/ocr_cache")
